// Code generated by MockGen. DO NOT EDIT.
// Source: business/reviews/domain.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reviews "finalProject/business/reviews"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockUsecase) Fetch(ctx context.Context, page, perpage int) ([]reviews.Domain, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, page, perpage)
	ret0, _ := ret[0].([]reviews.Domain)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Fetch indicates an expected call of Fetch.
func (mr *MockUsecaseMockRecorder) Fetch(ctx, page, perpage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockUsecase)(nil).Fetch), ctx, page, perpage)
}

// GetAll mocks base method.
func (m *MockUsecase) GetAll(ctx context.Context) ([]reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUsecaseMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUsecase)(nil).GetAll), ctx)
}

// GetByDescription mocks base method.
func (m *MockUsecase) GetByDescription(ctx context.Context, articlesDescription string) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDescription", ctx, articlesDescription)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDescription indicates an expected call of GetByDescription.
func (mr *MockUsecaseMockRecorder) GetByDescription(ctx, articlesDescription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDescription", reflect.TypeOf((*MockUsecase)(nil).GetByDescription), ctx, articlesDescription)
}

// GetByID mocks base method.
func (m *MockUsecase) GetByID(ctx context.Context, articlesId int) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, articlesId)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsecaseMockRecorder) GetByID(ctx, articlesId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsecase)(nil).GetByID), ctx, articlesId)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, articlesDomain *reviews.Domain, userId int) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, articlesDomain, userId)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, articlesDomain, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, articlesDomain, userId)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, articlesDomain *reviews.Domain) (*reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, articlesDomain)
	ret0, _ := ret[0].(*reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, articlesDomain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, articlesDomain)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockRepository) Fetch(ctx context.Context, page, perpage int) ([]reviews.Domain, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, page, perpage)
	ret0, _ := ret[0].([]reviews.Domain)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Fetch indicates an expected call of Fetch.
func (mr *MockRepositoryMockRecorder) Fetch(ctx, page, perpage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockRepository)(nil).Fetch), ctx, page, perpage)
}

// Find mocks base method.
func (m *MockRepository) Find(ctx context.Context) ([]reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx)
	ret0, _ := ret[0].([]reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), ctx)
}

// GetByDescription mocks base method.
func (m *MockRepository) GetByDescription(ctx context.Context, articlesDescription string) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDescription", ctx, articlesDescription)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDescription indicates an expected call of GetByDescription.
func (mr *MockRepositoryMockRecorder) GetByDescription(ctx, articlesDescription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDescription", reflect.TypeOf((*MockRepository)(nil).GetByDescription), ctx, articlesDescription)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, articlesId int) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, articlesId)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, articlesId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, articlesId)
}

// Store mocks base method.
func (m *MockRepository) Store(ctx context.Context, articlesDomain *reviews.Domain) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, articlesDomain)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockRepositoryMockRecorder) Store(ctx, articlesDomain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockRepository)(nil).Store), ctx, articlesDomain)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, articlesDomain *reviews.Domain) (reviews.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, articlesDomain)
	ret0, _ := ret[0].(reviews.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, articlesDomain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, articlesDomain)
}
